---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: storaged-${MOLECULE_SCENARIO_NAME:-v7-custom}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-almalinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # BeeGFS v7 with custom configuration
        storaged_beegfs_version: "7.4.6"
        storaged_repo_url: "https://www.beegfs.io/release/beegfs_7.4.6"
        storaged_conn_storage_port_tcp: "9003"
        storaged_conn_storage_port_udp: "9003"
        storaged_conn_interfaces: ["eth0"]
        storaged_deploy_auth_file: false
        storaged_server_targets:
          - target_id: "5"
            device: "vdb"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: localhost
verifier:
  name: testinfra
  options:
    # Add verbosity for better debugging
    v: 1
