---
# NOTE: Client role testing is limited to configuration validation only
# Full integration testing (with cluster and kernel modules) is performed
# using the OpenStack-based tests in extensions/molecule/
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: client-${MOLECULE_SCENARIO_NAME:-default}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-almalinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # Configuration for validation testing (no actual cluster)
        client_beegfs_version: "7.4.4"
        client_repo_url: "https://www.beegfs.io/release/beegfs_7.4.4"
        client_start_services: false  # Don't start services in container tests
        client_deploy_auth_file: false
        client_dkms_install: false  # Don't build kernel modules in containers
        client_clusters:
          - sys_mgmtd_host: localhost
            client_dir_paths:
              - beegfs_path: test
                fs_path: /mnt/beegfs
verifier:
  name: testinfra
  options:
    # Add verbosity for better debugging
    v: 1
