---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mon-${MOLECULE_SCENARIO_NAME:-v7-custom}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-almalinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # BeeGFS v7 with custom configuration
        mon_beegfs_version: "7.4.6"
        mon_repo_url: "https://www.beegfs.io/release/beegfs_7.4.6"
        mon_conn_mgmtd_port_tcp: "9008"
        mon_conn_mgmtd_port_udp: "9008"
        mon_conn_interfaces: ["eth0"]
        mon_deploy_auth_file: false
        mon_start_services: true
verifier:
  name: testinfra
  options:
    # Add verbosity for better debugging
    v: 1
