---
client_start_services: true
client_enable_beeond: false
client_auth_file_path: "{{ role_path }}/files/conn.auth"
client_clusters: []
client_dkms_install: false
client_dir_paths: []

client_tls_tmp_dir: "/tmp"
client_tls_key_file: "cert.key"
client_tls_cert_file: "cert.pem"
client_enable_tls: true

# /etc/beegfs/beegfs-client-autobuild.conf
client_ofed_libs_path: ""
client_nvfs_libs_path: ""
client_nvidia_libs_path: ""
client_rdma_enabled: true
client_build_kernel_modules: true
client_install_kernel_dev: true

# /etc/beegfs/beegfs-helperd.conf /etc/beegfs/beegfs-client.conf
client_sys_mgmtd_host: localhost
client_conn_client_port_udp: "8004"
client_conn_helperd_port_tcp: "8006"
client_conn_mgmtd_port_tcp: "8008"
client_conn_mgmtd_port_udp: "8008"
client_conn_interfaces: []
client_conn_use_rdma: "true"
client_conn_tcp_fallback_enabled: "true"
client_conn_rdma_buf_num: "70"
client_conn_rdma_buf_size: "8192"
client_conn_max_internode_num: "12"
client_conn_rdma_meta_buf_num: "{{ client_conn_rdma_buf_num }}"
client_conn_rdma_meta_buf_size: "{{ client_conn_rdma_buf_size }}"
client_tune_file_cache_buf_size: "1048576"
client_quota_enabled: "false"
client_sys_xattrs_enabled: "false"
client_sys_acls_enabled: "false"
